# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sou < Formula
  desc "A TUI tool to explore container images"
  homepage "https://github.com/knqyf263/sou"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/knqyf263/sou/releases/download/v0.2.0/sou_Darwin_x86_64.tar.gz"
      sha256 "61582488e6dfab3e60fcd490ccbaccd92e7ba26bc96a6b6563b8e2f9be12fb7b"

      def install
        bin.install "sou"
      end
    end
    on_arm do
      url "https://github.com/knqyf263/sou/releases/download/v0.2.0/sou_Darwin_arm64.tar.gz"
      sha256 "79b19d1171b1ba8e411f0e0f2b2ffb00d480349d005bef42a59fe2562246da80"

      def install
        bin.install "sou"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.2.0/sou_Linux_x86_64.tar.gz"
        sha256 "a60a5c0ada9c6cbf9219ecc065f8b8c56cb64bdf91b468bcda638954e44d33c7"

        def install
          bin.install "sou"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.2.0/sou_Linux_arm64.tar.gz"
        sha256 "1af4e102a2fa9375e35499997cf84c5f33f61ab43be17c0039908b4af247b9de"

        def install
          bin.install "sou"
        end
      end
    end
  end

  test do
    system "#{bin}/sou --help"
  end
end
