# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sou < Formula
  desc "A TUI tool to explore container images"
  homepage "https://github.com/knqyf263/sou"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/knqyf263/sou/releases/download/v0.1.0/sou_Darwin_x86_64.tar.gz"
      sha256 "7266f9f1a4738f65770c8af3294b6ee5ce4aba11d3814c532d88d7a221b12088"

      def install
        bin.install "sou"
      end
    end
    on_arm do
      url "https://github.com/knqyf263/sou/releases/download/v0.1.0/sou_Darwin_arm64.tar.gz"
      sha256 "8d10780f611ce47e44fe52184fa87250f293f7641532e03822e185cca6d3e21a"

      def install
        bin.install "sou"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.1.0/sou_Linux_x86_64.tar.gz"
        sha256 "2b49050dccc4f4adb9790b2536b80feb1f1d78550fc57a6d172dfb4361460511"

        def install
          bin.install "sou"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.1.0/sou_Linux_arm64.tar.gz"
        sha256 "b1ac30c8f65acdf7eb3411973078d9ad664c2beb984a64f9c8e1f4a9937a8ede"

        def install
          bin.install "sou"
        end
      end
    end
  end

  test do
    system "#{bin}/sou --help"
  end
end
