# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sou < Formula
  desc "A TUI tool to explore container images"
  homepage "https://github.com/knqyf263/sou"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/knqyf263/sou/releases/download/v0.0.1/sou_Darwin_x86_64.tar.gz"
      sha256 "ab1c96746781a11bfb8c7bc8b39948d425942a188a2dd7dfdb3e797dfe25d687"

      def install
        bin.install "sou"
      end
    end
    on_arm do
      url "https://github.com/knqyf263/sou/releases/download/v0.0.1/sou_Darwin_arm64.tar.gz"
      sha256 "101031c93a8e9bb096f5de057fc19e279d0835d40855f23d5a40d0d96f0bfd65"

      def install
        bin.install "sou"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.0.1/sou_Linux_x86_64.tar.gz"
        sha256 "294046385f857c2039a39390e0d3636e190097695a03662e8acb7dc0d1910656"

        def install
          bin.install "sou"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/knqyf263/sou/releases/download/v0.0.1/sou_Linux_arm64.tar.gz"
        sha256 "916e9027d1052116165bfc3b3109d9dba8d324472ec23441955710e673ced340"

        def install
          bin.install "sou"
        end
      end
    end
  end

  test do
    system "#{bin}/sou --help"
  end
end
